spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/open436
    username: postgres
    password: Shicong666
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 16379
      password:
      timeout: 3000ms

logging:
  level:
    com.open436.auth: DEBUG
    cn.dev33.satoken: DEBUG
