spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db_test
    username: open436
    password: open436
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms

logging:
  level:
    com.open436.auth: INFO
